import os

file_path = r"c:\Users\Sagar Dagle\.gemini\antigravity\scratch\insurance-renewal-app\backend\src\main\resources\data.sql"
backup_path = file_path + ".bak_garbage_clean"

def is_garbage(line):
    # Check for specific garbage patterns generated by the broken script
    if "VALUES ('-', '.', '-', '0', '-')" in line:
        return True
    if "VALUES ('-', (SELECT id FROM customers WHERE email='-' LIMIT 1)" in line:
        return True
    if "VALUES ((SELECT id FROM policies WHERE policy_number='-')" in line:
        return True
    if "VALUES ('-'," in line and "LIMIT 1), '-', 0, NULL, 'EXPIRED'" in line: # policies variation
         return True
    return False

if not os.path.exists(file_path):
    print(f"File not found: {file_path}")
    exit(1)

print(f"Reading {file_path}...")
with open(file_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

new_lines = []
garbage_count = 0

for line in lines:
    if is_garbage(line):
        garbage_count += 1
        continue
    new_lines.append(line)

print(f"Found {garbage_count} garbage lines.")

if garbage_count > 0:
    print(f"Writing clean content to {file_path}...")
    with open(file_path, 'w', encoding='utf-8') as f:
        f.writelines(new_lines)
    print("Cleanup complete.")
else:
    print("No garbage found.")
